apiVersion: v1
kind: ConfigMap
metadata:
  name: etkx-config
  namespace: etkx
data:
  SPRING_DATASOURCE_URL: "jdbc:sqlite:/app/data/etkx.db"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.sqlite.JDBC"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "none"
  API_BASE_URL: "https://etkx.bimmerz.app/api"
