apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etkx-sqlite-pvc
  namespace: etkx
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-rbd-sc
  resources:
    requests:
      storage: 10Gi
